### ISSUE TITLE
No more development ?

### ISSUE THREAD

**Issue by pfeatherstone** [tzcnt/TooManyCooks#17]
Hi @tzcnt . Have you abandoned development? I was really looking forward to a release.

**Comment by tzcnt** [comment]
Hey, thanks for reaching out. Since this past summer I have been dealing with some health issues that took me off the project for a bit. I do plan to continue this work.

Before my hiatus, I had attempted to create a comprehensive documentation suite. This led me to work on adding the next missing feature - heterogeneous awaiter combinators - which would support async cancellation or timeouts. I feel like this is a critical feature for real world async. Once this feature is complete, I think that will be sufficient for an initial release.

I'll make no promises at timelines, but given that it is now winter, it would be a good time for me to pick up this development again. Thanks for your support.
